rails_app/config/routes.rb
Rails.application.routes.draw do


  #get 'landlords/:id/larger_than_4_tenants', :to => 'landlords#larger_than_4_tenants', :as => :larger_than_4_tenants
  get '/landlords/index', :to => 'landlords#index', :as => :index
  post 'landlords/:id/props/new', :to => 'props#create'

  resources :landlords do
  	resources :props do 
  	  #resources :floor_plans, only: [:larger_than_4_tenants]
    end
  end
  resources :tenants
  #devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  root 'homepage#index'

end

rails_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_app/app/models/landlord.rb
class Landlord < ApplicationRecord
    belongs_to :user
    has_many :props
    has_many :tenents, through: :props
    validates :name, presence: true
end

rails_app/app/models/prop.rb
class Prop < ApplicationRecord 
    belongs_to :landlord
    validates :name, presence:  true 

end 

rails_app/app/models/property_manager.rb
class Propertymanager < ApplicationRecord
    belongs_to :user
    has_many :landlords
    has_many :props, through: :landlords
    validates :name, presence: true
end

rails_app/app/models/tenant.rb
class Tenant < ApplicationRecord
    belongs_to :landord
    belongs_to :property_manager
end

rails_app/app/models/user.rb
class User < ApplicationRecord
    enum role: [:property_manager, :landlord, :tenant]
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
   devise :omniauthable, :omniauth_providers => [:facebook]
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        end      
    end

    def superadmin? 
        self.role = 0
        self.save
    end

    def admin?
        binding.pry
        self.role = 1
        binding.pry
        self.save
    end

    def user?
        self.role = 2
        self.save
    end
end

rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

	def after_sign_in_path_for(resource)
	  request.env['omniauth.origin'] || root_path
	end

end

rails_app/app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
	def index
	end

end

rails_app/app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
  def about
  end

  def index
    @landlords = Landlord.all
    @props = Prop.all
    render :index
  end

  def new 
    @landlord = Landlord.new 
  end 

  def create 
    @landlord = Landlord.new(name: landlord_params[:name], user:current_user)
  
      if @landlord.save
        @landlord.user.admin?
          redirect_to landlord_path(@landlord)
      else 
        flash[:notice] = "An error occured, landlord was not saved"
        render :new
      end 
  end 

  def show
    @landlord = Landlord.find(params[:id])
    @props = @landlord.props.all 
  end 

  def destroy
  @landlord = Landlord.find(params[:id])
  @landlord.destroy
    redirect_to landlord_index_path
  end 


  def update
    @landlord.update(landlord_params)
      redirect_to landlord_path(@landlord)
  end 


  private

  def landlord_params
    params.require(:landlord).permit(:name)
  end 
end

rails_app/app/controllers/property_managers.rb
class Controller < ApplicationController
  def about
  end

  def index
    @property_managers = andlord.all
    @apartments = Apartment.all
    render :index
  end

  def new 
    @property_manager = andlord.new 
  end 

  def create 
    @property_manager = andlord.new(name: property_manager_params[:name], user:current_user)
      if @property_manager.save
          @property_manager.user.superadmin?
          redirect_to property_manager_path(@property_manager)
      else 
        flash[:notice] = "An error occured, property manager was not saved"
        render :new
      end 
  end 

  def show
    @property_manager = andlord.find(params[:id])
    @props = @property_manager.propss.all 
  end

  def property_manager_params
    params.require(:property_manager).permit(:name)
  end 
end

rails_app/app/controllers/props_controller.rb
class PropsController < ApplicationController
 

  def new 
     @landlord = Landlord.find(params[:landlord_id])
     @prop = Prop.new 
    
     @url = new_landlord_prop_path(@landlord)
     
  end
  
  def create
    @landlord = Landlord.find(params[:id])
    @prop = @landlord.props.build
    @prop.update_attributes(prop_params)
    if @prop.save 
      binding.pry
          redirect_to landlord_prop_path(@prop.landlord, @prop)
                      
    else 
          flash[:notice] = "This property could not be saved"
          redirect_to new_landlord_prop_path(@landlord)
    end 
  end 

  def update 
   # binding.pry
    @url = landlord_prop_path 

    @prop= Prop.find(params[:id])
    @prop.update_attributes(prop_params)
    binding.pry
    
    if @prop.save 
      flash[:notice] = "The property has been saved!"
      #binding.pry
         redirect_to landlord_path(@prop.landlord, @prop)
    else 
      flash[:notice] = "The property could not be saved"
      render :show
    end 
  end 

  def show 
    @prop = Prop.find(params[:id])
    @url = landlord_prop_path
=begin if @prop.floor_plans.size < @prop.num_of_floor_plans
        new_floor_plan_forms = @prop.num_of_floor_plans - @prop.floor_plans.size
        new_floor_plan_forms.times { @prop.floor_plans.build}
    end 
=end
  end 

  private 

  def prop_params 
    params.require(:prop).permit(:name, :address, :structure, :landlord_id )
  end 
end

rails_app/app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @tenant = tenant.new
  end
  def create
    @tenant = Tenant.new(name: tenant_params)[:name], user: current_user)
    if @tenant.save 
      @tenant.user.tenant_role
      redirect_to tenant_path(@tenant)
    else 
      flash[:notice] = "Error occured: Tenant not saved"
      redirect_to new_tenant_path 
    end 
  end 

  private

  def tenant_params
      params.require(:tenant).permit(:name, :apartment_id)
  end
end

rails_app/app/controllers/users/omni_auth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
  end

rails_app/app/helpers/apartments_helper.rb
module ApartmentsHelper
end

rails_app/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_app/app/helpers/floor_plan_helper.rb
module FloorPlanHelper
end

rails_app/app/helpers/landlords_helper.rb
module LandlordsHelper
end

rails_app/app/helpers/tenants_helper.rb
module TenantsHelper
end

rails_app/app/views/homepage/index.html.erb
<% if current_user %> 
    
        <% if current_user.role.nil? %>
            <div id="landlord_reg">
                <h3>Seems you are not currently an affliated landlord, click <%= link_to('here', new_landlord_path)%> to being your application </h3>
            </div>
        <%elsif current_user.role == 'property_manager' %>
                    <p>Welcome <%=Landlord.find(current_user.id).name%>! </p>
                    <%= link_to('Manage Landlords', index_path)%>
        <%elsif current_user.role == 'landlord' %>
                    <p>Thanks for being a <%=current_user.role%> with us!. </p>
                    <%= link_to('Manage properties', landlord_path(Landlord.find_by(user: current_user))) %>
        <%elsif%>
                    <p>this shouldnt be here</p>
        <%end%> 

<%end%> 

<h3>Welcome To Liberty Forge Reality</h2>

<p>Replace this area with api map from google</p>

<div id="contact">
    <h2>Contact US</h2>
        <ul>
            <li>Liberty Forge Reality is managed by Dillion Wheaton</li>
            <li>Serving your local Akron Area</li>
        </ul>
    <h3>Liberty Forge Reality</h3>
        <ul>
            <li>Address:</li>
            <li>Phone:</li>
            <li>Operating Hours
                <ol>
                    <li>1</li>
                    <li>2</li>
                    <li>3</li>
                    <li>4</li>
                    <li>5</li>
                </ol>
            </li>
        </ul>
        <a href="not_a_site.com">Place Funcitonal contact button Here</a>

rails_app/app/views/landlords/_form.html.erb
<%= form_for @landlord do |f| %>
        Name:  <%= f.text_field :name %><br />
        <br /> 
    <%= f.submit %>
<%end%>

rails_app/app/views/landlords/index.html.erb
<% if @landlords.size > 0  %>
        <%if current_user.role == 'landlord' %>
            <div id= "landlords">
                <p> All the landlords youre affliated with: </p>
                    <ul>
                        <% @landlords.each do |landlord| %>
                        <li><%= link_to landlord.name %></li>
                        <% end %>
                    </ul>
            </div>
        <%elsif current_user.role == 'property manager' %>
            <div id= "landlords">
                <p> All the landlords you are managing </p>
                    <ul>
                        <% @landlords.each do |landlord| %>
                        <li><%= link_to landlord.name %></li>
                        <li><%= link_to landlord.name %></li>
                        <% end %>
                    </ul>
            </div>
        <%elsif current_user.role == 'tenant' %>
            <div id= "landlords">
                <p> Your Landlord</p>
                    <ul>
                        <% @landlords.each do |landlord| %>
                        <li><%= link_to landlord.name %></li>
                        <% end %>
                    </ul>
            </div>
        <%else current_user.role.nil?%>
        <%= flash[:notice] = "An error occured, landlord was not saved" %>
        <% redirect_to root%>

                        
        <%end%>
            

    <%else%>
    <p>There are currently no landlords</p>
<%end%>

            

rails_app/app/views/landlords/new.html.erb
<h3>New Landlord Application</h3>
<%if @landlord.errors.any? %>
    <% @landlord.errors.full_messages.each do |error_message| %>
        This Went Wrong: <%= error_message %> <br />
    <%end%>
<%end%>

<%=render 'form', landlord: @landlord %>

rails_app/app/views/landlords/show.html.erb
<h3>Landlord Profile:</h3>
Name: <%= @landlord.name %>
<br />
<h4>Properties owned:</h4>
    <% if @props.empty? %>
     <p> It looks like you dont have any properties assigned at the moment, go ahead and apply for registration of property</p>
    <%else%>
        <p>Choose an Property to update or add a new property. </p>
        <ul>
            <% @props.each do |prop| %>
                <li><%= link_to prop.name, landlord_prop_path(@landlord, prop) %></li>
            <%end%>
        </ul>
    <%end%>
<%= link_to 'Add New Property', new_landlord_prop_path(@landlord) %>
<br />
<%= link_to 'View Landlords', index_path%>

rails_app/app/views/layouts/_header.html.erb
<nav class="">
    <ul>
        <% if current_user %>
            <p>Signed in as <%= "#{current_user.email}" %></p>
            <%= link_to("Sign out", destroy_user_session_path, :method => 'delete') %>
            <%= link_to("Home", root_path) %>
        <% else %>
            <%= link_to("Sign up", new_user_registration_path) %>
            <%= link_to("Sign in", new_user_session_path) %>
        <% end %>
    </ul>
</nav>

rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Liberty Forge Reality</title>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

rails_app/app/views/props/_form.html.erb
<%= form_for @prop, url: @url do |f| %>
    Name: <%= f.text_field :name %><br />
    Address: <%= f.text_field :address %><br />
    Property Type: <%=f.text_field :structure%><br />
   
    
    <%=f.submit%>
<%end%>

rails_app/app/views/props/new.html.erb
<div id="new_prop">
    <h3>Add New Property</h3>
</div>

<%= render 'form', Property: @prop %>

rails_app/app/views/props/show.html.erb
<% if flash[:notice] %>
    <div class="warning"><%= flash[:notice] %></div>
<%end%>
<%if @prop.errors.any? %>
    <% @prop.errors.full_messages.each do |error_message| %>
        This issue occurred: <%= error_message %><br />
    <%end%>
<%end%>
<h3 hidden>Update this Property and add new detials </h3>
    <%= render 'form', Property: @prop%>